// Generated by CoffeeScript 1.7.1
(function() {
  define(['odo/hub'], function(hub) {
    var Game;
    return Game = (function() {
      function Game() {
        hub.once('Game start', function(m, cb) {
          hub.emit('Player 1 choose deck');
          return cb();
        });
        hub.once('Player 1 has chosen {deck} deck', function(m, cb) {
          hub.emit('Player 2 choose deck');
          return cb();
        });
        hub.once(['Player 1 has chosen {deck} deck', 'Player 2 has chosen {deck} deck'], function(m, cb) {
          hub.emit('Randomly select starting player');
          return cb();
        });
        hub.once('Player 2 will start', function(m, cb) {
          console.log('Player 2 starting');
          return cb();
        });
      }

      return Game;

    })();
  });

}).call(this);
