// Generated by CoffeeScript 1.7.1
(function() {
  define(['infra/hub'], function(hub) {
    var Game;
    Game = (function() {
      function Game() {
        hub.saga(['Game start'], function() {
          return hub.emit('Player 1 choose deck');
        });
        hub.saga(['Player 1 has chosen {deck} deck'], function() {
          return hub.emit('Player 2 choose deck');
        });
        hub.saga(['Player 1 has chosen {deck} deck', 'Player 2 has chosen {deck} deck'], function() {
          return hub.emit('Randomly select starting player');
        });
      }

      return Game;

    })();
    return new Game();
  });

}).call(this);
