// Generated by CoffeeScript 1.7.1
(function() {
  var args;

  module.exports = function(contexts) {
    var requirejs;
    requirejs = require('requirejs');
    requirejs.config({
      nodeRequire: require,
      paths: {
        odo: "" + __dirname + "/node_modules/odo",
        local: "" + __dirname + "/"
      }
    });
    return requirejs(['odo/bootstrap'], function(b) {
      return b(contexts);
    });
  };

  args = process.argv.slice(2);

  if (args.length > 0) {
    module.exports(args);
  }

}).call(this);
