// Generated by CoffeeScript 1.7.1
(function() {
  var requirejs;

  requirejs = require('requirejs');

  requirejs.config({
    nodeRequire: require
  });

  requirejs(['infra/cson', 'infra/hub'], function(cson, hub) {
    return cson('config.cson', function(config) {
      var s;
      return requirejs((function() {
        var _i, _len, _ref, _results;
        _ref = config.systems;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          s = _ref[_i];
          _results.push("" + s + "/" + s);
        }
        return _results;
      })(), function() {
        var e, _i, _len, _ref, _results;
        _ref = config.events;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          e = _ref[_i];
          _results.push(hub.emit(e.n, e.p));
        }
        return _results;
      });
    });
  });

}).call(this);
