// Generated by CoffeeScript 1.7.1
(function() {
  define(['infra/hub', 'cson'], function(hub, CSON) {
    return function(path, cb) {
      return CSON.parseFile(path, (function(_this) {
        return function(err, data) {
          if (err != null) {
            return hub.emit('error', "Bad " + path);
          }
          return cb(data);
        };
      })(this));
    };
  });

}).call(this);
