// Generated by CoffeeScript 1.7.1
(function() {
  define(function() {
    return {
      bg: color(43, 48, 59),
      gold: color(236, 204, 128),
      blue: color(142, 161, 180),
      red: color(193, 96, 100),
      purple: color(181, 141, 174),
      grey: color(192, 197, 206)
    };
  });

}).call(this);
