// Generated by CoffeeScript 1.7.1
(function() {
  define('plugins', ['statistics', 'ai', 'physics', 'coordinates', 'display']);

  define('game', ['inject', 'plugins'], function(inject) {
    var e, name, _, _i, _results;
    _results = [];
    for (_ = _i = 0; _i <= 50; _ = ++_i) {
      e = {};
      name = 'boid';
      inject.one('register ai')(e, name);
      inject.one('register statistics')(e, name);
      inject.one('register physics')(e, p5.Vector.random2D());
      inject.one('register coordinates')(e, createVector(random(width), random(height)));
      _results.push(inject.one('register display')(e, name));
    }
    return _results;
  });

  window.setup = function() {
    createCanvas(windowWidth, windowHeight);
    requirejs.config({
      urlArgs: 'v=' + (new Date()).getTime()
    });
    return requirejs(['inject', 'game'], function(inject) {
      return window.draw = function() {
        var exec, _i, _len, _ref, _results;
        _ref = inject.many('step');
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          exec = _ref[_i];
          _results.push(exec());
        }
        return _results;
      };
    });
  };

}).call(this);
