// Generated by CoffeeScript 1.7.1
(function() {
  define('plugins', ['statistics', 'ai', 'physics', 'display']);

  define('game', ['inject', 'plugins'], function(inject) {
    var e, name, _, _i, _results;
    _results = [];
    for (_ = _i = 0; _i <= 5; _ = ++_i) {
      e = {};
      name = 'boid';
      inject.one('register ai')(e, name);
      inject.one('register statistics')(e);
      inject.one('register physics')(e, 'circle', createVector(random(width), random(height)), p5.Vector.random2D());
      _results.push(inject.one('register display')(e, name));
    }
    return _results;
  });

  window.setup = function() {
    createCanvas(windowWidth, windowHeight);
    requirejs.config({
      urlArgs: 'v=' + (new Date()).getTime()
    });
    return requirejs(['inject', 'game'], function(inject) {
      var setup, _i, _len, _ref;
      _ref = inject.many('setup');
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        setup = _ref[_i];
        setup();
      }
      return window.draw = function() {
        var step, _j, _len1, _ref1, _results;
        _ref1 = inject.many('step');
        _results = [];
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          step = _ref1[_j];
          _results.push(step());
        }
        return _results;
      };
    });
  };

}).call(this);
