// Generated by CoffeeScript 1.7.1
(function() {
  define(['module', 'fs', 'csv', 'odo/hub', 'odo/delay'], function(module, fs, csv, hub, delay) {
    var Decks;
    return Decks = (function() {
      function Decks() {
        var path;
        this.decks = {};
        path = module.uri.split('/');
        path.pop();
        path.push('cards.csv');
        path = path.join('/');
        console.log(path);
        fs.readFile(path, {
          encoding: 'utf-8'
        }, (function(_this) {
          return function(err, cards) {
            return csv.parse(cards, {
              columns: true
            }, function(err, data) {
              return console.log(data);
            });
          };
        })(this));
        hub.every('{deck} deck has been created', (function(_this) {
          return function(p, cb) {
            _this.decks[p.deck] = {
              deck: p.deck
            };
            return cb();
          };
        })(this));
        hub.every('{deck} deck has new cards {cards}', (function(_this) {
          return function(p, cb) {
            _this.decks[p.deck].cards = p.cards;
            return cb();
          };
        })(this));
        hub.every('Player 1 choose deck', (function(_this) {
          return function(m, cb) {
            var add, deck, name, options, _ref;
            options = {};
            add = function(deck) {
              return options[deck.deck] = function() {
                return hub.emit('Player 1 has chosen {deck} deck', {
                  deck: deck.deck
                });
              };
            };
            _ref = _this.decks;
            for (name in _ref) {
              deck = _ref[name];
              add(deck);
            }
            console.log('Player 1 choose a deck');
            hub.emit('Player 1 select from options', options);
            return cb();
          };
        })(this));
        hub.every('Player 2 choose deck', (function(_this) {
          return function(m, cb) {
            var add, deck, name, options, _ref;
            options = {};
            add = function(deck) {
              return options[deck.deck] = function() {
                return hub.emit('Player 2 has chosen {deck} deck', {
                  deck: deck.deck
                });
              };
            };
            _ref = _this.decks;
            for (name in _ref) {
              deck = _ref[name];
              add(deck);
            }
            console.log('Player 2 choose a deck');
            hub.emit('Player 2 select from options', options);
            return cb();
          };
        })(this));
      }

      return Decks;

    })();
  });

}).call(this);
