// Generated by CoffeeScript 1.7.1
(function() {
  define(['infra/hub', 'infra/delay'], function(hub, delay) {
    var Decks;
    Decks = (function() {
      function Decks() {
        this.decks = {};
        hub.every('{deck} deck has been created', (function(_this) {
          return function(p) {
            return _this.decks[p.deck] = {
              deck: p.deck
            };
          };
        })(this));
        hub.every('{deck} deck has new cards {cards}', (function(_this) {
          return function(p) {
            return _this.decks[p.deck].cards = p.cards;
          };
        })(this));
        hub.every('Player 1 choose deck', (function(_this) {
          return function() {
            var add, deck, name, options, _ref;
            options = {};
            add = function(deck) {
              return options[deck.deck] = function() {
                return hub.emit('Player 1 has chosen {deck} deck', {
                  deck: deck.deck
                });
              };
            };
            _ref = _this.decks;
            for (name in _ref) {
              deck = _ref[name];
              add(deck);
            }
            console.log('Player 1 choose a deck');
            return hub.emit('Player 1 select from options', options);
          };
        })(this));
        hub.every('Player 2 choose deck', (function(_this) {
          return function() {
            var add, deck, name, options, _ref;
            options = {};
            add = function(deck) {
              return options[deck.deck] = function() {
                return hub.emit('Player 2 has chosen {deck} deck', {
                  deck: deck.deck
                });
              };
            };
            _ref = _this.decks;
            for (name in _ref) {
              deck = _ref[name];
              add(deck);
            }
            console.log('Player 2 choose a deck');
            return hub.emit('Player 2 select from options', options);
          };
        })(this));
      }

      return Decks;

    })();
    return new Decks();
  });

}).call(this);
