// Generated by CoffeeScript 1.7.1
(function() {
  define(['infra/hub', 'infra/cson'], function(hub, cson) {
    var Decks;
    Decks = (function() {
      function Decks() {
        this.decks = {};
        hub.on('{deck} deck has been created', (function(_this) {
          return function(p) {
            return _this.decks[p.deck] = {};
          };
        })(this));
        hub.on('{deck} deck has new cards {cards}', (function(_this) {
          return function(p) {
            return _this.decks[p.deck].cards = p.cards;
          };
        })(this));
      }

      return Decks;

    })();
    return new Decks();
  });

}).call(this);
